name: build

on:
  push:
    paths:
      - "**.pcss"
      - "**.png"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: npm ci
        run: npm ci
      - name: build
        run: npm run build
      - name: ls
        run: ls -la dist/
      - name: cp
        run: cp dist/main.css docs/main.css
      - uses: stefanzweifel/git-auto-commit-action@v4.10.0
        with:
          commit_message: update outcome
          file_pattern: docs/main.css
